// Copyright 2026 Apple Inc.
//
// Use of this source code is governed by a BSD-3-clause license that can
// be found in the LICENSE file or at https://opensource.org/licenses/BSD-3-Clause

import Foundation
import Testing

@testable import CoreAILanguageModels

/// Bit-exact parity for the DiffusionGemma entropy-renoise sampler vs the python reference
/// (`_diffgemma_sampler.py`, itself verified 9/9 vs HF `generation_diffusion_gemma.py`).
/// Loads a fixture generated by `_diffgemma_sampler_fixture.py` (synthetic seeded inputs +
/// expected outputs, cross-checked against HF) and checks temperature, entropy, accept
/// mask/canvas, renoise, and stable+confident stopping.
@Suite struct DiffusionSamplerTests {

    struct Fixture: Decodable {
        struct Config: Decodable {
            let CL: Int, VOCAB: Int, N: Int
            let EB: Float, TMIN: Float, TMAX: Float
            let STAB: Int, CONF: Float
        }
        struct Temp: Decodable { let cur_step: Int, t: Float }
        struct Accept: Decodable {
            let logits: [Float], current: [Int32], denoiser: [Int32]
            let entropy: [Float], accepted_mask: [Int], accepted_canvas: [Int32]
        }
        struct Renoise: Decodable { let random_canvas: [Int32], renoised_canvas: [Int32] }
        struct Stop: Decodable { let tag: String, logits: [Float], argmax: [Int32], expected_stop: Bool }
        let config: Config
        let temperature: [Temp]
        let accept: Accept
        let renoise: Renoise
        let stopping: [Stop]
    }

    static func loadFixture() throws -> Fixture {
        let url = try #require(
            Bundle.module.url(forResource: "diffusion_sampler_fixture", withExtension: "json"),
            "diffusion_sampler_fixture.json missing from test bundle")
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    @Test func temperatureSchedule() throws {
        let fx = try Self.loadFixture()
        for t in fx.temperature {
            let mine = linearTemperature(
                curStep: t.cur_step, tMin: fx.config.TMIN, tMax: fx.config.TMAX,
                maxDenoisingSteps: fx.config.N)
            #expect(abs(mine - t.t) < 1e-6, "temp@step\(t.cur_step): mine=\(mine) ref=\(t.t)")
        }
    }

    @Test func acceptEntropyMaskAndCanvas() throws {
        let fx = try Self.loadFixture()
        let cfg = fx.config

        // entropy parity (tolerance: fp reduction order differs from torch)
        let ent = categoricalEntropy(logits: fx.accept.logits, count: cfg.CL, vocab: cfg.VOCAB)
        for i in 0..<cfg.CL {
            #expect(abs(ent[i] - fx.accept.entropy[i]) < 1e-3,
                    "entropy[\(i)]: mine=\(ent[i]) ref=\(fx.accept.entropy[i])")
        }

        var s = EntropyBoundSampler(
            entropyBound: cfg.EB, canvasLength: cfg.CL, vocabSize: cfg.VOCAB, maxDenoisingSteps: cfg.N)
        let accepted = s.acceptCanvas(
            current: fx.accept.current, denoiser: fx.accept.denoiser, logits: fx.accept.logits, curStep: cfg.N)
        let mineMask = s.acceptedTokenMask.map { $0 ? 1 : 0 }
        #expect(mineMask == fx.accept.accepted_mask, "accepted_mask: mine=\(mineMask) ref=\(fx.accept.accepted_mask)")
        #expect(accepted == fx.accept.accepted_canvas, "accepted_canvas mismatch")
    }

    @Test func renoiseSelectsRejectsFromRandomCanvas() throws {
        let fx = try Self.loadFixture()
        let cfg = fx.config
        var s = EntropyBoundSampler(
            entropyBound: cfg.EB, canvasLength: cfg.CL, vocabSize: cfg.VOCAB, maxDenoisingSteps: cfg.N)
        // Reproduce the accept state so acceptedTokenMask matches the fixture, then renoise with
        // the python-dumped random canvas (Swift can't reproduce torch's randint stream).
        let accepted = s.acceptCanvas(
            current: fx.accept.current, denoiser: fx.accept.denoiser, logits: fx.accept.logits, curStep: cfg.N)
        let renoised = s.renoiseCanvas(accepted: accepted, randomCanvas: fx.renoise.random_canvas)
        #expect(renoised == fx.renoise.renoised_canvas, "renoised_canvas mismatch")
    }

    @Test func stableAndConfidentStopping() throws {
        let fx = try Self.loadFixture()
        let cfg = fx.config
        var stop = StableAndConfidentStopping(stabilityThreshold: cfg.STAB, confidenceThreshold: cfg.CONF)
        for c in fx.stopping {  // replayed in order through ONE instance (history matters)
            let mine = stop(argmaxCanvas: c.argmax, logits: c.logits, vocab: cfg.VOCAB)
            #expect(mine == c.expected_stop, "stop[\(c.tag)]: mine=\(mine) ref=\(c.expected_stop)")
        }
    }
}
